# Generated by Django 2.2.7 on 2019-12-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestpost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guestspeakingapplication',
            name='application_message',
            field=models.CharField(default='helloworld', max_length=200),
            preserve_default=False,
        ),
    ]
