# Generated by Django 2.2.7 on 2019-12-31 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest_posting', '0002_auto_20191231_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestpost',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='guestpost',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_podcast', to='podcasts.Podcast'),
        ),
        migrations.AlterField(
            model_name='guestpost',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='guestspeakingapplication',
            name='application_message',
            field=models.CharField(max_length=500),
        ),
    ]
