# Generated by Django 2.2.7 on 2019-12-31 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_posting', '0003_auto_20191231_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestpost',
            old_name='title',
            new_name='heading',
        ),
    ]
