# Generated by Django 2.2.7 on 2019-12-31 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_posting', '0004_auto_20191231_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestspeakingapplication',
            old_name='owner',
            new_name='applicant',
        ),
    ]
