# Generated by Django 2.2.7 on 2020-01-01 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest_posting', '0005_auto_20191231_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestpost',
            name='episode_airing_date',
        ),
        migrations.AlterField(
            model_name='guestpost',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guestpost',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.Podcast'),
        ),
        migrations.AlterField(
            model_name='guestspeakingapplication',
            name='application_message',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
