# Generated by Django 2.2.7 on 2020-01-01 13:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('guest_posting', '0006_auto_20200101_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestpost',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
