# Generated by Django 2.2.7 on 2020-01-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_posting', '0007_auto_20200101_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestpost',
            name='only_podcasters_can_apply',
            field=models.BooleanField(default=True),
        ),
    ]
