# Generated by Django 2.2.7 on 2019-12-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollaborationRequest',
        ),
    ]
