# Generated by Django 2.2.7 on 2019-11-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_collaborationboardpost_comment_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='publication_ptr',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='author',
        ),
        migrations.DeleteModel(
            name='CollaborationBoardPost',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
