# Generated by Django 2.2.7 on 2019-11-20 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20191120_1859'),
        ('users', '0005_auto_20191120_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationrequest',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='req_receiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='related_board_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='publications.CollaborationBoardPost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='req_sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
