# Generated by Django 2.2.7 on 2019-11-21 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191120_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborationrequest',
            name='related_board_post',
        ),
        migrations.RemoveField(
            model_name='collaborationrequest',
            name='text',
        ),
    ]
