# Generated by Django 2.2.7 on 2020-02-08 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import podcasts.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rss_feed_url', models.CharField(max_length=300)),
                ('rss_confirmation_code', models.CharField(default=podcasts.utils.generate_confirmation_code, max_length=8)),
                ('pending', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('image_link', models.CharField(max_length=300)),
                ('site_link', models.CharField(max_length=500)),
                ('confirmation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='podcasts.PodcastConfirmation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
