# Generated by Django 2.2.7 on 2020-02-09 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_auto_20200208_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastPublishingLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apple_podcast', models.CharField(default='', max_length=200)),
                ('spotify', models.CharField(default='', max_length=200)),
                ('website', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='podcast',
            name='publishing_links',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='podcasts.PodcastPublishingLinks'),
            preserve_default=False,
        ),
    ]
