# Generated by Django 2.2.7 on 2020-02-09 11:13

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_auto_20200209_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='publishing_links',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to='podcasts.PodcastPublishingLinks'),
        ),
    ]
