# Generated by Django 2.2.7 on 2019-12-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_podcast_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='confirmation',
        ),
    ]
