# Generated by Django 2.2.7 on 2020-02-09 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_auto_20200209_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='publishing_links',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='podcasts.PodcastPublishingLinks'),
        ),
    ]
