# Generated by Django 2.2.7 on 2019-12-29 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_remove_podcast_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='confirmation',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='podcasts.PodcastConfirmation'),
            preserve_default=False,
        ),
    ]
