# Generated by Django 2.2.7 on 2019-11-20 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='publication',
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_publication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commented_pub', to='publications.Publication'),
            preserve_default=False,
        ),
    ]
